name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Ninja
        run: sudo apt install ninja-build -y

      - name: Clone beeflang
        run: git clone --recursive https://github.com/beefytech/Beef.git

      - name: Build llvm
        run: cd Beef/extern && bash ./llvm_build.sh
        
      - name: Create package
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: 'Beef/extern/'
          filename: 'llvm-dist.zip'
        
      - name: Remove old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: llvm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Beef/extern/llvm-dist.zip"
          name: 'llvm-dist'
          prerelease: true
          tag: llvm-dist
          token: ${{ secrets.GITHUB_TOKEN }}
